import fs from 'node:fs';
import assert from 'node:assert/strict';
import {parseCsv,toCsv,mergeDraws,frequency,euroPoolAt,ranking,generateTickets,backtest,intersection,prizeTier} from './core.mjs';
const csv=fs.readFileSync(new URL('./data/eurojackpot.csv',import.meta.url),'utf8');
const {draws,invalid}=parseCsv(csv);
assert.equal(invalid,0);assert.equal(draws.length,128);
assert.equal(draws[0].date,'2025-07-18');assert.equal(draws.at(-1).date,'2026-10-06');
assert.equal(euroPoolAt('2013-12-01'),8);assert.equal(euroPoolAt('2014-10-10'),10);assert.equal(euroPoolAt('2022-03-25'),12);
assert.deepEqual(parseCsv(toCsv(draws)).draws,draws);
const parsed= parseCsv('datum;z1;z2;z3;z4;z5;eurozahlen;wochentag;jahr\n29.09.2026;21;30;36;43;48;1-5;Dienstag;2026');
assert.deepEqual(parsed.draws[0].euro,[1,5]);
assert.equal(parseCsv('date,n1,n2,n3,n4,n5,e1,e2\n2026-01-01,1,2,3,4,5,12,12').draws.length,0);
assert.equal(parseCsv('date,n1,n2,n3,n4,n5,e1,e2\n2013-01-01,1,2,3,4,5,9,10').draws.length,0);
assert.equal(parseCsv('date,n1,n2,n3,n4,n5,e1,e2\n2026-02-30,1,2,3,4,5,1,2').draws.length,0);
assert.equal(mergeDraws(draws,draws).added,0);
assert.equal(frequency(draws,'main',75).reduce((x,o)=>x+o.count,0),75*5);
assert.equal(frequency(draws,'euro',75).reduce((x,o)=>x+o.count,0),75*2);
const opts={count:6,strategy:'trend',filter:true,pool:12,maxOverlap:2};
const first=generateTickets(draws,opts);const second=generateTickets(draws,opts);
assert.deepEqual(first.tickets,second.tickets);
assert.equal(first.tickets.length,6);
assert(first.tickets.every(t=>t.main.length===5&&new Set(t.main).size===5&&t.euro.length===2&&new Set(t.euro).size===2));
assert(first.tickets.every(t=>t.main.every(n=>!first.blacklist.includes(n))));
for(let i=0;i<first.tickets.length;i++)for(let j=i+1;j<first.tickets.length;j++)assert(intersection(first.tickets[i].main,first.tickets[j].main)<=2);
assert.equal(prizeTier(5,2),1);assert.equal(prizeTier(2,1),12);assert.equal(prizeTier(0,0),null);
const result=backtest(draws,{...opts,testDraws:50});
assert.equal(result.tested,50);
assert.equal(result.first,draws.at(-50).date);assert.equal(result.last,'2026-10-06');
assert.equal(Object.values(result.model.matrix).reduce((a,b)=>a+b,0),300);
assert.equal(Object.values(result.baseline.matrix).reduce((a,b)=>a+b,0),300);
assert.equal(result.model.totalMain>=0,true);
// Simulate a single prediction with all available earlier history: no access to the last draw.
const past=draws.slice(0,-1),pred=generateTickets(past,opts);
assert(pred.tickets.every(t=>t.main.every(n=>n>=1&&n<=50)));
console.log(`OK: ${draws.length} valid draws, CSV import/export, rule eras, portfolio overlaps, 50-draw walk-forward test, random baseline, no-peeking split.`);
console.log(`Model: 3+ main hits ${result.model.threePlus}; random: ${result.baseline.threePlus}; test period ${result.first} – ${result.last}`);
